# project/configs/service.yaml

paths:
  artifacts_dir: "artifacts" # Можно хардкодить, так как это внутренняя структура проекта
  model_file: "best_model.pkl"
  scaler_file: "scaler.pkl"

server:
  host: "0.0.0.0"
  port: 8000
  title: "Bank Customer Segmentation API"
  version: "1.0.0"