# project/docker-compose.yml

version: '3.8'

services:
  bank-api:
    # Собираем образ из текущего Dockerfile
    build: .
    
    # Название контейнера для удобства
    container_name: bank-segmentation-service
    
    # Пробрасываем порт: 8000 на вашем компьютере -> 8000 внутри контейнера
    ports:
      - "8000:8000"
      
    # Переменные окружения
    # Мы берем их из файла .env в корневой папке
    env_file:
      - .env
      
    # Дополнительные переменные, если нужно переопределить пути внутри контейнера
    environment:
      - PYTHONUNBUFFERED=1  # Чтобы логи выводились сразу, а не буферизировались
      
    # Монтирование томов (опционально, но полезно для разработки)
    # Если вы хотите, чтобы изменения в коде подхватывались без пересборки образа, раскомментируйте строки ниже:
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./artifacts:/app/artifacts  # Чтобы модель сохранялась на вашем ПК, а не внутри временного контейнера