services:
  train-job:
    build: .
    
    container_name: bank-train-job
    
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
      

    env_file:
      - .env
    
    command: ["python", "-m", "src.bank_segmentation.cli", "train"]