version: '3.8'

services:
  bank-api:
    build: .
    
    container_name: bank-segmentation-service
    
    ports:
      - "8000:8000"
      
    # Переменные окружения
    # Мы берем их из файла .env в корневой папке
    env_file:
      - .env
      
    environment:
      - PYTHONUNBUFFERED=1
    
    volumes:
      - ./src:/app/src
      - ./configs:/app/configs
      - ./artifacts:/app/artifacts